// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvAWnErqoPgxT3q23mca3ddExLmy_As4c',
    appId: '1:187778246473:web:9939b5fdae6ea8524d9c98',
    messagingSenderId: '187778246473',
    projectId: 'preronapath',
    authDomain: 'preronapath.firebaseapp.com',
    storageBucket: 'preronapath.firebasestorage.app',
    measurementId: 'G-T4Y2XK4GLQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBR3MIKPGLhA7FHPlWFJcR3lV5m9_aDbyw',
    appId: '1:187778246473:android:a8c745a6f296c7564d9c98',
    messagingSenderId: '187778246473',
    projectId: 'preronapath',
    storageBucket: 'preronapath.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_LD9cwmmlrwyAw_i0oQQaLxvrMcyFwig',
    appId: '1:187778246473:ios:f5966a092f577eaf4d9c98',
    messagingSenderId: '187778246473',
    projectId: 'preronapath',
    storageBucket: 'preronapath.firebasestorage.app',
    androidClientId: '187778246473-a5r2mmen39c8rf1vqmb2dpdi2uk6sc70.apps.googleusercontent.com',
    iosClientId: '187778246473-diluucjf5ilotmej6slufgvaec5sj8ae.apps.googleusercontent.com',
    iosBundleId: 'com.example.preronapath',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_LD9cwmmlrwyAw_i0oQQaLxvrMcyFwig',
    appId: '1:187778246473:ios:f5966a092f577eaf4d9c98',
    messagingSenderId: '187778246473',
    projectId: 'preronapath',
    storageBucket: 'preronapath.firebasestorage.app',
    androidClientId: '187778246473-a5r2mmen39c8rf1vqmb2dpdi2uk6sc70.apps.googleusercontent.com',
    iosClientId: '187778246473-diluucjf5ilotmej6slufgvaec5sj8ae.apps.googleusercontent.com',
    iosBundleId: 'com.example.preronapath',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAvAWnErqoPgxT3q23mca3ddExLmy_As4c',
    appId: '1:187778246473:web:9c93506860fef48b4d9c98',
    messagingSenderId: '187778246473',
    projectId: 'preronapath',
    authDomain: 'preronapath.firebaseapp.com',
    storageBucket: 'preronapath.firebasestorage.app',
    measurementId: 'G-FWNWM3MT2K',
  );
}
